export const products = [
  {
    id: 1,
    name: "Winter body",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "ارسال رایگان" },
      { support: "اورجینال" },
    ],
    category : "newArrivals",
    price: 120,
    offPrice: 120,
    discount: 0,
    image: "https://s8.uupload.ir/files/court-vision-mid-next-nature-mens-shoes-j5k4rb_8sqw.jpg",
  },
  {
    id: 2,
    name: "Adidas",
    description: [{ support: "گارانتی مادام العمر" }, { support: "اورجینال" }],
    price: 110,
    offPrice: 100,
    discount: 8,
    category : "newArrivals",
    image: "https://s8.uupload.ir/files/air-max-systm-mens-shoes-twglwk_n8p.jpg",
  },
  {
    id: 3,
    name: "Vans",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 99,
    offPrice: 89,
    discount: 10,
    category : "topRated",
    image: "https://s8.uupload.ir/files/giannis-immortality-2-basketball-shoes-x7xj7b_p1we.jpg",
  },
  {
    id: 4,
    name: "White",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 260,
    offPrice: 220,
    discount: 15,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/phantom-gt2-academy-dynamic-fit-mg-multi-ground-soccer-cleats-rwrt6t_p778.jpg",
  },
  {
    id: 5,
    name: "Croopped-shoe",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 150,
    offPrice: 150,
    discount: 0,
    category : "topRated",
    image: "https://s8.uupload.ir/files/renew-elevate-3-basketball-shoes-bq8xtz_z9fg.jpg",
  },
  {
    id: 6,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/renew-elevate-3-basketball-shoes-bq8xtz_2_bex4.jpg",
  },
  {
    id: 7,
    name: "New Shoes",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/asuna-2-mens-slides-8zn47w_zi4e.jpg",
  },
  {
    id: 8,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/giannis-immortality-2-basketball-shoes-x7xj7b_htm3.jpg",
  },
  {
    id: 9,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/quest-4-mens-road-running-shoes-rlplvs_8jft.jpg",
  },
  {
    id: 10,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/retro-gts-mens-shoe-7qkpwq_xbb0.jpg",
  },
  {
    id: 11,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/revolution-5-mens-road-running-shoes-zxqs6c_gq3m.jpg",
  },
  {
    id: 12,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/sb-force-58-premium-skate-shoes-qp1tsm_a1o5.jpg",
  },
  {
    id: 13,
    name: "Blues",
    description: [
      { support: "گارانتی مادام العمر" },
      { support: "اورجینال" },
      { support: "ارسال رایگان" },
    ],
    price: 220,
    offPrice: 200,
    discount: 13,
    category : "bestSellers",
    image: "https://s8.uupload.ir/files/wio-9-mens-road-running-shoes-zlblt0_z7qz.jpg",
  },
];

